### ISSUE TITLE
Use case for a high-resolution timer

### ISSUE THREAD

**Issue by seamusdemora** [Blimp01/pico_non_blocking_timer#4]
Pardon me if I've missed something, but I need to ask a question that may save me some time: 

As background, I learned of your project from [this post in the rpi forums](https://forums.raspberrypi.com/viewtopic.php?f=145&t=304201&p=1820770&hilit=Hermannsw+systick#p1822677).

I have a need for a fairly high-resolution timer to decode the [WWVB signal](https://www.nist.gov/pml/time-and-frequency-division/radio-stations/wwvb/wwvb-time-code-format). To be clear, the resolution needed is much greater than the duration of the lowest-duration symbol (200 msec); i.e. the duration can be used as a temporal filter. 

All of that said, do you feel your non-blocking timer code here is a reasonable fit for my use-case?

**Comment by Blimp01** [comment]
Hello,

So the resoultion of this timer is setup to 1ms. You can change this resolution by changing the rwr value in non_blocking.c . The current configuration is:

`` (125Mhz)/ (124999UL+ 1) = 1ms.``

So in theory if you needed a 0.5ms resolution for your application you could set this up. (However it will need a bit of testing, you dont want a interrupt happening so often that you never execute any other code). - ive done this before, its a pain to debug.

Otherwise 1ms resoultions should be okay for a 200ms signal. 

Hope this helps,

Blimp01 :)
